# Create container with:
# docker build -t her .
# Run container with (replacing /path/to/hindsight/repo):
# docker run --privileged --rm -v /path/to/hindsight/repo:/root --runtime nvidia --network host --name herdev -it her
# It's easier if you put "export HER_PATH=/path/to/hindsight/repo:/root" in your ~/.bash_profile and run
# docker run --privileged --rm -v $HER_PATH:/root --runtime nvidia --network host --name herdev -it her

# This preinstalls pytorch, python, pip3. 
FROM nvcr.io/nvidia/l4t-pytorch:r32.4.4-pth1.6-py3

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -y
RUN apt-get upgrade -y

# libopenmpi-dev is required for mpi4py
RUN apt-get install -y libopenmpi-dev

# Repo requirements
RUN pip3 -vv install mpi4py
# This takes ~30 mins. -vv makes it print more data so you know it still working
RUN pip3 -vv install gym

# Useful tools. More will likely need to be added.
RUN apt-get install -y git man curl gdb openssh-client vim

# Setup openblas
ENV OPENBLAS_DIR=/opt/openblas
RUN mkdir $OPENBLAS_DIR
RUN git clone https://github.com/xianyi/OpenBLAS
WORKDIR /OpenBLAS
# This is the nonthreaded version of openblas (see: https://github.com/bgeneto/build-install-compile-openblas)
RUN make -j DYNAMIC_ARCH=0 CC=gcc FC=gfortran HOSTCC=gcc BINARY=64 INTERFACE=64 NO_AFFINITY=1 NO_WARMUP=1 USE_OPENMP=0 USE_THREAD=0 USE_LOCKING=1
RUN make PREFIX=$OPENBLAS_DIR install
WORKDIR /
